// Exercise library — built from research Teil 5 (Übungsdatenbank). Each entry
// carries Heim-/No-Equipment-Varianten. Order within a category runs leicht →
// schwer, which also drives the in-app difficulty. Names bilingual; instruction
// text is German (the app's primary locale for v1).
import type { Domain } from '@/domain/models';

export interface Exercise {
  id: string;
  name: { de: string; en: string };
  domain: Domain;
  difficulty: 1 | 2 | 3;
  quality: string; // dosage label, e.g. "Kraft"
  steps: string[];
  formTips: string[];
  mistakes: string[];
  variants: { gym: string; home: string; none: string };
  dosage: { intensity: string; reps: string; sets: string; rest: string };
}

const D = {
  kraft: { intensity: '70–85%', reps: '6–8', sets: '3–4', rest: '2–3′' },
  maxkraft: { intensity: '85–92%', reps: '3–5', sets: '4–5', rest: '3′' },
  power: { intensity: '30–60%', reps: '3–6', sets: '3–5', rest: '2–3′' },
  speed: { intensity: 'max', reps: '5–20 m', sets: '6–10', rest: '3–5′' },
  agility: { intensity: 'max', reps: '3–6', sets: '3–5', rest: '90″–2′' },
  core: { intensity: 'Körpergew.', reps: '8–15', sets: '2–3', rest: '60–90″' },
  prehab: { intensity: 'leicht', reps: '12–15', sets: '2–3', rest: '45–60″' },
  mobility: { intensity: '–', reps: '5–8/Seite', sets: '1–2', rest: 'gering' },
  kondition: { intensity: 'hart', reps: '20–30 s', sets: '6–8', rest: '1:2–1:3' },
};

export const EXERCISES: Exercise[] = [
  // ── 5.1 Beinkraft ─────────────────────────────────────────────────────────
  {
    id: 'bodyweight-squat', name: { de: 'Körpergewicht-Kniebeuge', en: 'Bodyweight Squat' }, domain: 'powerLower', difficulty: 1, quality: 'Kraft',
    steps: ['Füße schulterbreit, Zehen leicht nach außen.', 'Hüfte nach hinten und runter in die Hocke.', 'Über die ganze Fußsohle hochdrücken.'],
    formTips: ['Brust offen, Rücken neutral.', 'Knie folgen der Zehenrichtung.'],
    mistakes: ['Fersen heben ab.', 'Knie kippen nach innen.'],
    variants: { gym: 'Vor dem Spiegel zur Technikkontrolle.', home: 'Überall, ggf. an Stuhllehne abstützen.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.kraft,
  },
  {
    id: 'glute-bridge', name: { de: 'Glute Bridge', en: 'Glute Bridge' }, domain: 'powerLower', difficulty: 1, quality: 'Kraft',
    steps: ['Rücklings, Füße hüftbreit aufgestellt.', 'Hüfte hoch, Po oben fest anspannen.', 'Kontrolliert absenken, knapp über den Boden.'],
    formTips: ['Bewegung kommt aus dem Po, nicht dem Rücken.', 'Rippen unten lassen, kein Hohlkreuz.'],
    mistakes: ['Überstrecken im unteren Rücken.', 'Po-Spannung oben fehlt.'],
    variants: { gym: 'Mit Mini-Band über den Knien.', home: 'Rucksack auf der Hüfte für mehr Last.', none: 'Einbeinig für mehr Intensität.' },
    dosage: D.kraft,
  },
  {
    id: 'box-squat', name: { de: 'Box Squat', en: 'Box Squat' }, domain: 'powerLower', difficulty: 1, quality: 'Kraft',
    steps: ['Box/Stuhl hinter dir, Füße schulterbreit.', 'Kontrolliert auf die Box absetzen.', 'Ohne Schwung wieder explosiv hoch.'],
    formTips: ['Kurz auf der Box, nicht zurücklehnen.', 'Schienbein bleibt stabil.'],
    mistakes: ['Auf die Box plumpsen lassen.', 'Mit Schwung hochwippen.'],
    variants: { gym: 'Plyo-Box auf Zieltiefe.', home: 'Stuhl oder Couch als Box.', none: 'Auf eine Treppenstufe absetzen.' },
    dosage: D.kraft,
  },
  {
    id: 'goblet-squat', name: { de: 'Goblet Squat', en: 'Goblet Squat' }, domain: 'powerLower', difficulty: 1, quality: 'Kraft',
    steps: ['Gewicht vor der Brust halten, Füße schulterbreit.', 'Tief in die Hocke, Knie Richtung Zehen.', 'Explosiv hoch, oben Po anspannen.'],
    formTips: ['Fersen am Boden, Brust aufrecht.', 'Knie nicht nach innen kippen lassen.'],
    mistakes: ['Rücken rundet sich unten.', 'Nur halbe Tiefe.'],
    variants: { gym: 'Kurzhantel/Kettlebell vor der Brust.', home: 'Rucksack mit Büchern vor der Brust.', none: 'Körpergewicht, Arme nach vorn gestreckt.' },
    dosage: D.kraft,
  },
  {
    id: 'reverse-lunge', name: { de: 'Ausfallschritt rückwärts', en: 'Reverse Lunge' }, domain: 'powerLower', difficulty: 2, quality: 'Kraft',
    steps: ['Aus dem Stand einen großen Schritt zurück.', 'Hinteres Knie Richtung Boden senken.', 'Über die vordere Ferse zurück in den Stand.'],
    formTips: ['Oberkörper aufrecht, Rumpf fest.', 'Vorderes Knie stabil über dem Fuß.'],
    mistakes: ['Vorderes Knie kippt nach innen.', 'Zu kleiner Schritt, Knie schiebt vor.'],
    variants: { gym: 'Kurzhanteln in beiden Händen.', home: 'Rucksack als Zusatzlast.', none: 'Körpergewicht, Hände an die Hüfte.' },
    dosage: D.kraft,
  },
  {
    id: 'lateral-lunge', name: { de: 'Seitlicher Ausfallschritt', en: 'Lateral Lunge' }, domain: 'powerLower', difficulty: 2, quality: 'Kraft',
    steps: ['Breiter Schritt zur Seite.', 'Über das belastete Bein in die Hocke, anderes Bein gestreckt.', 'Kraftvoll zurück zur Mitte abdrücken.'],
    formTips: ['Court-spezifisch: Adduktoren & Frontalebene.', 'Hüfte nach hinten, Brust auf.'],
    mistakes: ['Knie schiebt über die Zehen hinaus.', 'Oberkörper kippt seitlich weg.'],
    variants: { gym: 'Kurzhantel im Goblet-Griff.', home: 'Rucksack vor der Brust.', none: 'Körpergewicht, Arme als Ausgleich.' },
    dosage: D.kraft,
  },
  {
    id: 'step-up', name: { de: 'Step-Up', en: 'Step-Up' }, domain: 'powerLower', difficulty: 2, quality: 'Kraft',
    steps: ['Einen Fuß komplett auf die Box stellen.', 'Über die Ferse hochdrücken, Standbein streckt.', 'Kontrolliert wieder absteigen.'],
    formTips: ['Kraft kommt vom oberen Bein, nicht vom Abdruck unten.', 'Hüfte und Knie auf einer Linie.'],
    mistakes: ['Mit dem unteren Bein hochstoßen.', 'Box zu hoch, Technik bricht.'],
    variants: { gym: 'Plyo-Box + Kurzhanteln.', home: 'Treppe oder stabiler Stuhl + Rucksack.', none: 'Treppe, nur Körpergewicht.' },
    dosage: D.kraft,
  },
  {
    id: 'db-rdl', name: { de: 'KH-Rumänisches Kreuzheben', en: 'Dumbbell RDL' }, domain: 'powerLower', difficulty: 2, quality: 'Kraft',
    steps: ['Gewichte vor den Oberschenkeln, Knie leicht gebeugt.', 'Hüfte nach hinten, Gewicht nah am Bein nach unten.', 'Über die Hüfte zurück nach oben.'],
    formTips: ['Hintere Kette: Hamstrings & Po.', 'Rücken bleibt die ganze Zeit neutral.'],
    mistakes: ['Rücken rundet sich.', 'Bewegung aus dem Knie statt der Hüfte.'],
    variants: { gym: 'Kurzhanteln oder Langhantel.', home: 'Wasserkanister in beiden Händen.', none: 'Einbeinig ohne Gewicht.' },
    dosage: D.kraft,
  },
  {
    id: 'heavy-squat-deadlift', name: { de: 'Schwere Kniebeuge / Trap-Bar', en: 'Heavy Squat / Trap-Bar Deadlift' }, domain: 'powerLower', difficulty: 3, quality: 'Maximalkraft',
    steps: ['Last sicher aufnehmen, Rumpf maximal anspannen.', 'Kontrolliert in die Hocke / Hüfte laden.', 'Explosiv die volle Hüft- und Kniestreckung.'],
    formTips: ['Maximalkraftbasis – Technik vor Last.', 'Volle Spannung von Anfang bis Ende.'],
    mistakes: ['Last zu schwer, Form bricht.', 'Rücken verliert die Neutralstellung.'],
    variants: { gym: 'Langhantel-Kniebeuge oder Trap-Bar.', home: 'Schwerstes mögliches Goblet.', none: 'Langsame Tempo-Pistols / einbeinig.' },
    dosage: D.maxkraft,
  },
  {
    id: 'hip-thrust', name: { de: 'Hip Thrust', en: 'Hip Thrust' }, domain: 'powerLower', difficulty: 2, quality: 'Kraft',
    steps: ['Schultern erhöht, Füße aufgestellt.', 'Hüfte hoch, oben Po fest anspannen.', 'Kontrolliert absenken.'],
    formTips: ['Rippen unten lassen, kein Hohlkreuz.', 'Schienbein senkrecht oben.'],
    mistakes: ['Überstrecken im unteren Rücken.', 'Nicht voll hochdrücken.'],
    variants: { gym: 'Langhantel/Kurzhantel auf der Hüfte.', home: 'Rucksack auf der Hüfte, Schultern auf Couch.', none: 'Körpergewicht, ggf. einbeinig.' },
    dosage: D.kraft,
  },
  {
    id: 'bulgarian-split-squat', name: { de: 'Bulgarian Split Squat', en: 'Bulgarian Split Squat' }, domain: 'powerLower', difficulty: 2, quality: 'Kraft',
    steps: ['Hinteres Bein erhöht ablegen.', 'Vorderes Knie tief beugen.', 'Über die vordere Ferse hochdrücken.'],
    formTips: ['Rumpf leicht vorgeneigt, stabil.', 'Vorderes Knie stabil über dem Fuß.'],
    mistakes: ['Gewicht auf der hinteren Fußspitze.', 'Knie kippt nach innen.'],
    variants: { gym: 'Kurzhanteln in beiden Händen.', home: 'Hinteres Bein auf Couch/Stuhl.', none: 'Körpergewicht, Hände an die Hüfte.' },
    dosage: D.kraft,
  },
  {
    id: 'single-leg-rdl', name: { de: 'Einbeiniges RDL', en: 'Single-leg RDL' }, domain: 'powerLower', difficulty: 3, quality: 'Kraft',
    steps: ['Auf einem Bein stehen, Standbein leicht gebeugt.', 'Hüfte nach hinten, Oberkörper kippt vor.', 'Über die Hüfte zurück nach oben.'],
    formTips: ['Korrigiert L/R-Asymmetrie.', 'Rücken neutral, Hüfte führt die Bewegung.'],
    mistakes: ['Rücken rundet sich.', 'Hüfte rotiert auf.'],
    variants: { gym: 'Kurzhantel in der Gegenhand.', home: 'Wasserkanister/Rucksack als Gewicht.', none: 'Körpergewicht, Arme als Ausgleich.' },
    dosage: D.kraft,
  },

  // ── 5.2 Oberkörper & Schulter + Prehab ────────────────────────────────────
  {
    id: 'scapular-retraction', name: { de: 'Schulterblatt-Retraktion', en: 'Scapular Retraction' }, domain: 'powerUpper', difficulty: 1, quality: 'Prehab',
    steps: ['Band auf Brusthöhe greifen, Arme lang.', 'Schulterblätter nach hinten-unten ziehen.', 'Kurz halten, langsam lösen.'],
    formTips: ['Bewegung nur aus den Schulterblättern.', 'Schultern weg von den Ohren.'],
    mistakes: ['Mit den Armen ziehen.', 'Schultern hochziehen.'],
    variants: { gym: 'Am Kabel oder Band.', home: 'Tube-Band an der Türklinke.', none: 'Aktive Retraktion ohne Last (Wall-Slides).' },
    dosage: D.prehab,
  },
  {
    id: 'sleeper-stretch', name: { de: 'Sleeper-Stretch', en: 'Sleeper Stretch' }, domain: 'mobility', difficulty: 1, quality: 'Mobility',
    steps: ['Seitlage, unterer Arm 90° nach vorn.', 'Mit der freien Hand den Unterarm sanft Richtung Boden drücken.', 'Dehnung halten, ruhig atmen.'],
    formTips: ['Gegen GIRD (Innenrotationsdefizit).', 'Sanft – nie in den Schmerz.'],
    mistakes: ['Zu kräftig drücken.', 'Schulterblatt rollt nach vorn.'],
    variants: { gym: 'Auf der Matte im Prehab-Bereich.', home: 'Überall am Boden.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.mobility,
  },
  {
    id: 'cross-body-stretch', name: { de: 'Cross-Body-Adduktionsstretch', en: 'Cross-Body Stretch' }, domain: 'mobility', difficulty: 1, quality: 'Mobility',
    steps: ['Arm gestreckt vor die Brust führen.', 'Mit dem anderen Arm sanft heranziehen.', 'Dehnung der hinteren Schulter halten.'],
    formTips: ['Schulter unten lassen.', 'Ergänzt den Sleeper-Stretch.'],
    mistakes: ['Schulter zieht zum Ohr hoch.', 'Rumpf dreht mit.'],
    variants: { gym: 'Zwischen den Sätzen.', home: 'Überall ohne Equipment.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.mobility,
  },
  {
    id: 'band-external-rotation-0', name: { de: 'Band-Außenrotation @0°', en: 'Band External Rotation @0°' }, domain: 'powerUpper', difficulty: 1, quality: 'Prehab',
    steps: ['Ellbogen am Körper, 90° gebeugt.', 'Unterarm gegen das Band nach außen.', 'Langsam und kontrolliert zurück.'],
    formTips: ['Ellbogen bleibt fix am Körper.', 'Manschette als Abbremser stärken.'],
    mistakes: ['Ellbogen wandert weg.', 'Zu schweres Band.'],
    variants: { gym: 'Kabelzug niedrig, leicht.', home: 'Tube-/Mini-Band am Türgriff.', none: 'Isometrisch gegen die andere Hand.' },
    dosage: D.prehab,
  },
  {
    id: 'prone-ytw', name: { de: 'Prone Y-T-W', en: 'Prone Y-T-W' }, domain: 'powerUpper', difficulty: 2, quality: 'Prehab',
    steps: ['Bäuchlings, Stirn auf der Matte.', 'Arme nacheinander zu Y, T und W heben.', 'Oben kurz halten, langsam senken.'],
    formTips: ['Unterer & mittlerer Trapez.', 'Daumen nach oben, Schultern tief.'],
    mistakes: ['Schultern hochziehen.', 'Mit Schwung reißen.'],
    variants: { gym: 'Auf der Schrägbank, leichte KH.', home: 'Bäuchlings mit kleinen Wasserflaschen.', none: 'Ohne Gewicht, nur Bewegung.' },
    dosage: D.prehab,
  },
  {
    id: 'serratus-punch', name: { de: 'Serratus-Punch / Push-up-Plus', en: 'Serratus Punch' }, domain: 'powerUpper', difficulty: 2, quality: 'Prehab',
    steps: ['Plank- oder Stützposition.', 'Oberen Rücken nach oben „rausschieben".', 'Schulterblätter auseinanderziehen, halten.'],
    formTips: ['Serratus anterior für Schulterblatt-Stabilität.', 'Bewegung kommt nur aus den Schulterblättern.'],
    mistakes: ['Im unteren Rücken durchhängen.', 'Mit den Armen drücken.'],
    variants: { gym: 'Mit Band um den oberen Rücken.', home: 'Push-up-Plus am Boden oder an der Wand.', none: 'Wall-Slides mit Protraktion.' },
    dosage: D.prehab,
  },
  {
    id: 'band-row', name: { de: 'Band-/Ruderzug', en: 'Band / Cable Row' }, domain: 'powerUpper', difficulty: 2, quality: 'Kraft',
    steps: ['Band/Griff auf Bauchhöhe greifen.', 'Ellbogen eng am Körper nach hinten ziehen.', 'Schulterblätter zusammen, langsam zurück.'],
    formTips: ['Ziehen > Drücken – Balance für die Schulter.', 'Brust auf, Rumpf stabil.'],
    mistakes: ['Mit dem Rücken schwingen.', 'Schultern hochziehen.'],
    variants: { gym: 'Kabelrudern oder Langhantelrudern.', home: 'Band um einen Türanker.', none: 'Inverted Row an stabiler Tischkante.' },
    dosage: D.kraft,
  },
  {
    id: 'face-pull', name: { de: 'Face Pull', en: 'Face Pull' }, domain: 'powerUpper', difficulty: 2, quality: 'Prehab',
    steps: ['Band auf Augenhöhe fixieren.', 'Zum Gesicht ziehen, Ellbogen hoch.', 'Außenrotation oben betonen, langsam lösen.'],
    formTips: ['Gegen Innenrotationsdominanz.', 'Schulterblätter nach hinten-unten.'],
    mistakes: ['Ellbogen fallen ab.', 'Last zu schwer, keine Außenrotation.'],
    variants: { gym: 'Kabelzug mit Seil.', home: 'Band über der Tür fixieren.', none: 'Band-Pull-aparts als Ersatz.' },
    dosage: D.prehab,
  },
  {
    id: 'band-external-rotation-90', name: { de: 'Band-Außenrotation @90°', en: 'Band External Rotation @90°' }, domain: 'powerUpper', difficulty: 2, quality: 'Prehab',
    steps: ['Oberarm 90° abgespreizt, Ellbogen gebeugt.', 'Unterarm gegen das Band nach oben/hinten rotieren.', 'Kontrolliert in die Aufschlagposition und zurück.'],
    formTips: ['Spezifisch für die Aufschlag-/Wurfposition.', 'Schulterblatt stabil halten.'],
    mistakes: ['Ellbogen sinkt unter 90°.', 'Ruckartig statt kontrolliert.'],
    variants: { gym: 'Kabel auf Schulterhöhe.', home: 'Band auf Schulterhöhe am Türanker.', none: 'Langsame Außenrotation ohne Last.' },
    dosage: D.prehab,
  },
  {
    id: 'push-up', name: { de: 'Liegestütz', en: 'Push-up' }, domain: 'powerUpper', difficulty: 2, quality: 'Kraft',
    steps: ['Hände etwas weiter als schulterbreit.', 'Körper als Brett kontrolliert absenken.', 'Kraftvoll nach oben drücken.'],
    formTips: ['Rumpf fest, Hüfte in einer Linie.', 'Ellbogen ca. 45° am Körper.'],
    mistakes: ['Hüfte hängt durch.', 'Nur halbe Bewegungsamplitude.'],
    variants: { gym: 'Füße erhöht oder mit Zusatzlast.', home: 'Incline an der Tischkante (leichter).', none: 'Auf den Knien oder an der Wand.' },
    dosage: D.kraft,
  },
  {
    id: 'single-arm-row', name: { de: 'Einarm-KH-Rudern', en: 'Single-arm DB Row' }, domain: 'powerUpper', difficulty: 2, quality: 'Kraft',
    steps: ['Eine Hand abgestützt, Rücken flach.', 'Gewicht eng am Körper nach oben ziehen.', 'Schulterblatt zusammen, langsam ablassen.'],
    formTips: ['Rumpf stabil, kein Rotieren.', 'Aus dem Rücken ziehen, nicht dem Arm.'],
    mistakes: ['Oberkörper dreht auf.', 'Mit Schwung reißen.'],
    variants: { gym: 'Kurzhantel auf der Bank abgestützt.', home: 'Rucksack, an Stuhl abgestützt.', none: 'Inverted Row einarmig an der Tischkante.' },
    dosage: D.kraft,
  },
  {
    id: 'overhead-press', name: { de: 'Überkopfdrücken', en: 'Overhead Press' }, domain: 'powerUpper', difficulty: 3, quality: 'Kraft',
    steps: ['Gewicht auf Schulterhöhe, Rumpf fest.', 'Gerade nach oben drücken.', 'Kontrolliert zurück auf Schulterhöhe.'],
    formTips: ['Nur bei gesunder, schmerzfreier Manschette.', 'Rippen unten, kein Hohlkreuz.'],
    mistakes: ['Ins Hohlkreuz ausweichen.', 'Bei Schulterschmerz weitermachen.'],
    variants: { gym: 'Kurzhanteln oder Langhantel.', home: 'Landmine-Press oder Rucksack.', none: 'Pike-Push-ups als Ersatz.' },
    dosage: D.kraft,
  },
  {
    id: 'd2-pnf', name: { de: 'Diagonales D2-PNF-Muster', en: 'D2 PNF Pattern' }, domain: 'powerUpper', difficulty: 3, quality: 'Prehab',
    steps: ['Start: Hand an der Gegenhüfte, Faust geschlossen.', 'Diagonal nach oben-außen ziehen, Hand öffnet.', 'Kontrolliert in die Startdiagonale zurück.'],
    formTips: ['Bildet das Wurf-/Aufschlagmuster nach.', 'Volle Diagonale, sauber geführt.'],
    mistakes: ['Bewegung zu klein.', 'Last zu schwer, Muster bricht.'],
    variants: { gym: 'Kabel oder Band diagonal.', home: 'Band diagonal am Türanker.', none: 'Leichte KH/Wasserflasche im Muster.' },
    dosage: D.prehab,
  },

  // ── 5.3 Core & Anti-Rotation ──────────────────────────────────────────────
  {
    id: 'front-plank', name: { de: 'Front-Plank', en: 'Front Plank' }, domain: 'core', difficulty: 1, quality: 'Core',
    steps: ['Unterarmstütz, Ellbogen unter den Schultern.', 'Körper als gerade Linie spannen.', 'Position ruhig atmend halten.'],
    formTips: ['Anti-Extension: Po und Bauch fest.', 'Nacken lang, Blick zum Boden.'],
    mistakes: ['Hüfte sackt durch.', 'Po zu hoch gestreckt.'],
    variants: { gym: 'Füße erhöht oder mit Gewichtsscheibe.', home: 'Standard am Boden.', none: 'Auf den Knien (leichter).' },
    dosage: { intensity: 'Körpergew.', reps: '20–60 s', sets: '3', rest: '45–60″' },
  },
  {
    id: 'side-plank', name: { de: 'Side-Plank', en: 'Side Plank' }, domain: 'core', difficulty: 1, quality: 'Core',
    steps: ['Seitlage, Ellbogen unter der Schulter.', 'Hüfte hoch, Körper bildet eine Linie.', 'Halten, dann Seite wechseln.'],
    formTips: ['Anti-Lateralflexion: Hüfte oben halten.', 'Schulter stabil über dem Ellbogen.'],
    mistakes: ['Hüfte sinkt ab.', 'Körper kippt nach vorn/hinten.'],
    variants: { gym: 'Mit Beinheben oder Last.', home: 'Standard am Boden.', none: 'Unteres Knie ablegen (leichter).' },
    dosage: { intensity: 'Körpergew.', reps: '20–60 s/Seite', sets: '2–3', rest: '45″' },
  },
  {
    id: 'dead-bug', name: { de: 'Dead Bug', en: 'Dead Bug' }, domain: 'core', difficulty: 1, quality: 'Core',
    steps: ['Rücklings, Arme und Beine in 90°.', 'Gegengleich Arm und Bein ausstrecken.', 'Kontrolliert zurück, Seite wechseln.'],
    formTips: ['Unterer Rücken bleibt am Boden.', 'Langsam und kontrolliert atmen.'],
    mistakes: ['Hohlkreuz beim Strecken.', 'Zu schnell, ohne Spannung.'],
    variants: { gym: 'Mit leichtem Zusatzgewicht in den Händen.', home: 'Standard am Boden.', none: 'Nur Beine bewegen (leichter).' },
    dosage: D.core,
  },
  {
    id: 'bird-dog', name: { de: 'Bird Dog', en: 'Bird Dog' }, domain: 'core', difficulty: 1, quality: 'Core',
    steps: ['Vierfüßlerstand, Rücken neutral.', 'Gegengleich Arm und Bein lang strecken.', 'Kurz halten, kontrolliert zurück.'],
    formTips: ['Hüfte bleibt waagerecht – nicht aufdrehen.', 'Lange Linie von Hand zu Ferse.'],
    mistakes: ['Hüfte rotiert auf.', 'Rücken fällt ins Hohlkreuz.'],
    variants: { gym: 'Mit Mini-Band an Hand/Fuß.', home: 'Standard am Boden.', none: 'Erst nur Arm, dann nur Bein.' },
    dosage: D.core,
  },
  {
    id: 'band-anti-rotation-deadbug', name: { de: 'Band-Anti-Rotation Dead Bug', en: 'Band Anti-Rotation Dead Bug' }, domain: 'core', difficulty: 2, quality: 'Core',
    steps: ['Band seitlich greifen, Arme zur Decke.', 'Gegen den Zug die Rumpfspannung halten.', 'Beine wechselseitig absenken, Band ruhig halten.'],
    formTips: ['Rumpf widersteht der Rotation.', 'Unterer Rücken bleibt flach.'],
    mistakes: ['Oberkörper dreht zum Band.', 'Last zu hoch, Lendenwirbel hebt ab.'],
    variants: { gym: 'Kabel seitlich auf Bodenhöhe.', home: 'Band niedrig am Türanker.', none: 'Klassischer Dead Bug ohne Band.' },
    dosage: D.core,
  },
  {
    id: 'pallof-press', name: { de: 'Pallof Press', en: 'Pallof Press' }, domain: 'core', difficulty: 1, quality: 'Core',
    steps: ['Seitlich zum Band, Griff vor der Brust.', 'Arme gerade nach vorn drücken.', 'Halten, dann zurückführen.'],
    formTips: ['Flaggschiff Anti-Rotation – genau die Tennis-Aufgabe.', 'Hüfte stabil, Rumpf widersteht der Rotation.'],
    mistakes: ['Oberkörper dreht zum Band.', 'Schultern hochgezogen.'],
    variants: { gym: 'Kabelzug auf Brusthöhe.', home: 'Tube-Band an der Türklinke fixieren.', none: 'Isometrisch ohne Band (Rumpf bewusst spannen).' },
    dosage: D.core,
  },
  {
    id: 'standing-cable-rotation', name: { de: 'Stehende Band-/Kabel-Rotation', en: 'Standing Cable Rotation' }, domain: 'core', difficulty: 2, quality: 'Power',
    steps: ['Seitlich zum Band, Arme vor der Brust.', 'Aus der Hüfte kontrolliert wegrotieren.', 'Geführt zurück in die Ausgangsposition.'],
    formTips: ['Rotation aus Hüfte & Rumpf, nicht den Armen.', 'Füße fest, Becken stabil.'],
    mistakes: ['Nur die Arme schwingen.', 'Lendenwirbelsäule überdreht.'],
    variants: { gym: 'Kabel auf Brusthöhe.', home: 'Band auf Brusthöhe am Türanker.', none: 'Schattenrotation mit Rumpfspannung.' },
    dosage: D.core,
  },
  {
    id: 'medball-rotational-throw', name: { de: 'Med-Ball Rotationswurf', en: 'Med-ball Rotational Throw' }, domain: 'powerUpper', difficulty: 2, quality: 'Power',
    steps: ['Seitlich zur Wand, Ball auf Hüfthöhe.', 'Aus der Hüfte explosiv rotieren.', 'Ball kraftvoll gegen die Wand werfen.'],
    formTips: ['Bildet VH/RH nach – Kraft aus Beinen & Hüfte.', 'Locker und explosiv, nicht verkrampft.'],
    mistakes: ['Nur mit den Armen werfen.', 'Keine Hüftrotation.'],
    variants: { gym: 'Med-Ball (3–4 kg) gegen die Wand.', home: 'Leichter Ball/Rucksack, Schattenwurf.', none: 'Schattenrotation explosiv ohne Ball.' },
    dosage: D.power,
  },
  {
    id: 'medball-overhead-rotational-throw', name: { de: 'Overhead-Rotationswurf', en: 'Overhead Rotational Throw' }, domain: 'powerUpper', difficulty: 3, quality: 'Power',
    steps: ['Step-behind aufbauen, Ball über die Schulter laden.', 'Über die volle Kette Bein-Hüfte-Rumpf-Arm entladen.', 'Ball explosiv nach vorn/unten schleudern.'],
    formTips: ['Fortgeschritten: volle kinetische Kette.', 'Timing von unten nach oben.'],
    mistakes: ['Kette springt – nur Arm/Schulter.', 'Kein Step-behind, keine Beinkraft.'],
    variants: { gym: 'Med-Ball Slam/Wurf mit Step-behind.', home: 'Woodchop/Burpee mit Rucksack.', none: 'Explosiver Schatten-Overhead ohne Ball.' },
    dosage: D.power,
  },

  // ── 5.4 Explosive Power / Plyometrie ──────────────────────────────────────
  {
    id: 'pogo-hops', name: { de: 'Pogo Hops', en: 'Pogo Hops' }, domain: 'powerLower', difficulty: 1, quality: 'Power',
    steps: ['Aufrecht stehen, Beine fast gestreckt.', 'Aus dem Sprunggelenk klein und schnell hüpfen.', 'Bodenkontakt so kurz wie möglich.'],
    formTips: ['Steife Sprunggelenke, „heiß" vom Boden.', 'Aus dem Fußgelenk, nicht den Knien.'],
    mistakes: ['Tief in die Knie gehen.', 'Lange, weiche Bodenkontakte.'],
    variants: { gym: 'Auf weichem Boden / Matte.', home: 'Überall mit etwas Platz.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.power,
  },
  {
    id: 'jump-rope', name: { de: 'Seilspringen', en: 'Jump Rope' }, domain: 'powerLower', difficulty: 1, quality: 'Power',
    steps: ['Seil locker führen, Handgelenke drehen.', 'Kleine, schnelle Sprünge auf dem Vorfuß.', 'Gleichmäßiger Rhythmus.'],
    formTips: ['Elastische, kurze Bodenkontakte.', 'Aufrecht, Blick nach vorn.'],
    mistakes: ['Zu hoch springen.', 'Aus den Armen statt Handgelenken drehen.'],
    variants: { gym: 'Springseil im Warm-up.', home: 'Springseil oder Pogos ohne Seil.', none: 'Pogo Hops als Ersatz.' },
    dosage: D.power,
  },
  {
    id: 'cmj', name: { de: 'Counter-Movement Jump', en: 'Counter-Movement Jump' }, domain: 'powerLower', difficulty: 1, quality: 'Power',
    steps: ['Aus dem Stand kurz in die Hocke laden.', 'Sofort explosiv maximal hoch springen.', 'Weich und kontrolliert landen.'],
    formTips: ['Schnelle Gegenbewegung, dann voll explodieren.', 'Arme aktiv mitschwingen.'],
    mistakes: ['Zu langsame, tiefe Ausholbewegung.', 'Harte Landung.'],
    variants: { gym: 'Mit Mattenkontakt / Messung.', home: 'Überall mit Deckenhöhe.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.power,
  },
  {
    id: 'box-jump', name: { de: 'Box Jump', en: 'Box Jump' }, domain: 'powerLower', difficulty: 2, quality: 'Power',
    steps: ['Vor der Box, leicht laden.', 'Explosiv hoch und sauber auf die Box.', 'Weich landen, kontrolliert absteigen.'],
    formTips: ['Weiche Landung üben, nicht von der Box springen.', 'Hüfte oben voll strecken.'],
    mistakes: ['Box zu hoch, harte Landung.', 'Von der Box herunterspringen (Gelenkstress).'],
    variants: { gym: 'Plyo-Box auf passender Höhe.', home: 'Stabile, niedrige Stufe.', none: 'Tuck Jumps am Boden.' },
    dosage: D.power,
  },
  {
    id: 'broad-jump', name: { de: 'Standweitsprung', en: 'Broad Jump' }, domain: 'powerLower', difficulty: 2, quality: 'Power',
    steps: ['Aus dem Stand laden, Arme zurück.', 'Explosiv weit nach vorn springen.', 'Beidbeinig stabil landen und halten.'],
    formTips: ['Sehr tennisrelevant: horizontale Power.', 'Landung 1 s einfrieren.'],
    mistakes: ['Wegknicken bei der Landung.', 'Kein Armschwung.'],
    variants: { gym: 'Mit Markierung für Weite.', home: 'Im Park/Garten.', none: 'Identisch – nur Platz nötig.' },
    dosage: D.power,
  },
  {
    id: 'lateral-bound', name: { de: 'Lateral Bound', en: 'Lateral Bound' }, domain: 'powerLower', difficulty: 2, quality: 'Power',
    steps: ['Auf einem Bein, leicht in die Hocke.', 'Explosiv seitlich abspringen.', 'Auf dem anderen Bein stabil landen.'],
    formTips: ['Laterale Power + einbeiniges Abbremsen.', 'Landung 1 s halten, Knie stabil.'],
    mistakes: ['Wegknicken bei der Landung.', 'Kein Stoppen der Landung.'],
    variants: { gym: 'Über Markierungen/Hürden seitlich.', home: 'Über ein Handtuch seitlich springen.', none: 'Körpergewicht, seitliche Skater.' },
    dosage: D.power,
  },
  {
    id: 'medball-chest-pass', name: { de: 'Med-Ball Chest Pass', en: 'Med-ball Chest Pass' }, domain: 'powerUpper', difficulty: 2, quality: 'Power',
    steps: ['Ball vor der Brust, Athletikstand.', 'Explosiv geradeaus gegen die Wand stoßen.', 'Ball fangen, sofort wiederholen.'],
    formTips: ['Aus Brust und Beinen, voll durchstrecken.', 'Schnelle, reaktive Wiederholungen.'],
    mistakes: ['Nur aus den Armen drücken.', 'Zu langsame Ausführung.'],
    variants: { gym: 'Med-Ball gegen feste Wand.', home: 'Leichter Ball gegen die Wand.', none: 'Plyo-Liegestütz als Ersatz.' },
    dosage: D.power,
  },
  {
    id: 'medball-overhead-slam', name: { de: 'Med-Ball Overhead Slam', en: 'Med-ball Overhead Slam' }, domain: 'powerUpper', difficulty: 2, quality: 'Power',
    steps: ['Ball über den Kopf laden, Rumpf streckt.', 'Explosiv nach unten auf den Boden schlagen.', 'Aufnehmen und sofort wiederholen.'],
    formTips: ['Bildet das Aufschlagmuster nach.', 'Ganzkörper-Entladung, voll durchziehen.'],
    mistakes: ['Nur mit den Armen schlagen.', 'Rücken rundet beim Bücken.'],
    variants: { gym: 'Slam-Ball (springt nicht).', home: 'Burpee oder Woodchop mit Rucksack.', none: 'Explosiver Schatten-Slam ohne Ball.' },
    dosage: D.power,
  },
  {
    id: 'single-leg-box-jump', name: { de: 'Einbeiniger Box Jump / Bound', en: 'Single-leg Box Jump' }, domain: 'powerLower', difficulty: 3, quality: 'Power',
    steps: ['Auf einem Bein vor niedriger Box.', 'Explosiv einbeinig hoch und landen.', 'Stabilisieren, kontrolliert zurück.'],
    formTips: ['Unilaterale RFD, beide Seiten gleich trainieren.', 'Saubere, stabile Landung vor mehr Höhe.'],
    mistakes: ['Knie kippt bei der Landung ein.', 'Box zu hoch für die Kontrolle.'],
    variants: { gym: 'Niedrige Plyo-Box.', home: 'Niedrige Stufe.', none: 'Einbeinige Hops auf der Wiese.' },
    dosage: D.power,
  },
  {
    id: 'reactive-bound-cut', name: { de: 'Reaktiver Bound + Cut', en: 'Reactive Bound + Cut' }, domain: 'agility', difficulty: 3, quality: 'Power',
    steps: ['Seitlichen Bound springen und stabil landen.', 'Auf Signal sofort in einen Cut beschleunigen.', 'Wenige saubere, explosive Wiederholungen.'],
    formTips: ['Verbindet Plyo mit reaktiver Agilität.', 'Erst landen-stabilisieren, dann abdrücken.'],
    mistakes: ['Landung wird übersprungen.', 'Auf das Signal antizipiert statt reagiert.'],
    variants: { gym: 'Mit Hütchen + Partner-Signal.', home: 'Markierungen + Zuruf.', none: 'Selbst-Ansage als Signal.' },
    dosage: D.power,
  },
  {
    id: 'depth-jump', name: { de: 'Depth Jump', en: 'Depth Jump' }, domain: 'powerLower', difficulty: 3, quality: 'Power',
    steps: ['Von kleiner Box heruntertreten.', 'Bei Bodenkontakt sofort explosiv hoch.', 'Bodenkontakt so kurz wie möglich.'],
    formTips: ['Reaktive Kraft, fortgeschritten.', 'Minimaler Bodenkontakt, „heiß" abspringen.'],
    mistakes: ['Zu lange am Boden.', 'Zu hohe Box (Qualität leidet).'],
    variants: { gym: 'Plyo-Box 20–30 cm.', home: 'Untere Treppenstufe.', none: 'Reaktive Strecksprünge am Boden.' },
    dosage: D.power,
  },
  {
    id: 'contrast-depth-broad', name: { de: 'Kontrast: Depth → Broad Jump', en: 'Contrast: Depth → Broad Jump' }, domain: 'powerLower', difficulty: 3, quality: 'Power',
    steps: ['Depth Jump von der Box ausführen.', 'Direkt anschließend maximalen Standweitsprung.', 'Volle Pause, wenige Top-Wiederholungen.'],
    formTips: ['Kontrastmethode für maximale RFD.', 'Qualität vor Quantität – komplett erholt arbeiten.'],
    mistakes: ['Zu viele Wiederholungen, müde.', 'Pausen zu kurz.'],
    variants: { gym: 'Box + Markierung für Weite.', home: 'Niedrige Stufe + Park.', none: 'Tuck Jump → Broad Jump.' },
    dosage: D.power,
  },

  // ── 5.5 Schnelligkeit & Beschleunigung ────────────────────────────────────
  {
    id: 'a-march', name: { de: 'A-March', en: 'A-March' }, domain: 'speed', difficulty: 1, quality: 'Speed',
    steps: ['Aufrecht marschieren, Knie hoch zur Hüfte.', 'Fuß aktiv unter die Hüfte „klauen".', 'Arme im Sprintwinkel mitführen.'],
    formTips: ['Sauberes Sprint-ABC für die Technik.', 'Hoher Kniehub, fester Fuß.'],
    mistakes: ['Nach hinten lehnen.', 'Schlaffer Fußaufsatz.'],
    variants: { gym: 'Auf der Bahn / im Flur.', home: 'Auf der Stelle oder über 10 m.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.speed,
  },
  {
    id: 'a-skip', name: { de: 'A-Skip', en: 'A-Skip' }, domain: 'speed', difficulty: 1, quality: 'Speed',
    steps: ['Hüpfender Rhythmus mit hohem Knie.', 'Aktiver Fußaufsatz unter dem Körper.', 'Arme gegengleich, rhythmisch.'],
    formTips: ['Rhythmus & Frequenz schulen.', 'Vorfußkontakt, aufrechte Haltung.'],
    mistakes: ['Auf der Ferse landen.', 'Oberkörper kippt nach hinten.'],
    variants: { gym: 'Auf der Bahn.', home: 'Über 10–15 m.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.speed,
  },
  {
    id: 'wall-drive', name: { de: 'Wall Drive', en: 'Wall Drive' }, domain: 'speed', difficulty: 1, quality: 'Speed',
    steps: ['An die Wand gelehnt, Körper im Beschleunigungswinkel.', 'Knie abwechselnd kraftvoll hoch.', 'Fuß aktiv nach unten-hinten treiben.'],
    formTips: ['Trainiert den flachen Accel-Winkel.', 'Körper bleibt eine gerade Linie.'],
    mistakes: ['Hüfte knickt ein.', 'Nur das Knie heben, kein Abdruck.'],
    variants: { gym: 'Feste Wand / Geländer.', home: 'Hauswand oder Türrahmen.', none: 'Schräge Haltung ohne Wand halten.' },
    dosage: D.speed,
  },
  {
    id: 'falling-start', name: { de: 'Falling Start → 5 m', en: 'Falling Start → 5 m' }, domain: 'speed', difficulty: 2, quality: 'Speed',
    steps: ['Aufrecht stehen, langsam nach vorn kippen.', 'Im letzten Moment in den Sprint abfangen.', 'Über 5 m flach beschleunigen.'],
    formTips: ['Lehrt den flachen ersten Schritt.', 'Erst fallen lassen, dann explodieren.'],
    mistakes: ['Zu früh aufrichten.', 'Vorzeitig loslaufen.'],
    variants: { gym: 'Auf der Bahn.', home: 'Park / Court.', none: 'Identisch – nur Platz nötig.' },
    dosage: D.speed,
  },
  {
    id: 'accel-5-10', name: { de: '5 m & 10 m Accel', en: '5 m & 10 m Acceleration' }, domain: 'speed', difficulty: 2, quality: 'Speed',
    steps: ['Aus der Ready-Position vorspannen.', 'Explosiv und flach beschleunigen.', 'Über 5–10 m voll durchziehen.'],
    formTips: ['≥90 % Intensität, volle Erholung.', 'Aktiver Armeinsatz.'],
    mistakes: ['Zu kurze Pausen.', 'Zu früh aufrichten.'],
    variants: { gym: 'Hütchen als Marken.', home: 'Handy als Marke.', none: 'Markierungen mit Socken/Tape.' },
    dosage: D.speed,
  },
  {
    id: 'sprint-20m', name: { de: '20 m Sprint', en: '20 m Sprint' }, domain: 'speed', difficulty: 2, quality: 'Speed',
    steps: ['Aus 3-Punkt-Start vorspannen.', 'Explosiv beschleunigen, flacher Winkel.', 'Über 20 m voll durchziehen.'],
    formTips: ['Vollständige Pausen zwischen Läufen.', 'Arme aktiv mitführen.'],
    mistakes: ['Zu kurze Pausen (Speed leidet).', 'Aufrichten zu früh.'],
    variants: { gym: 'Halle/Bahn mit Markierungen.', home: 'Im Park / auf dem Court.', none: 'Identisch – nur Platz nötig.' },
    dosage: D.speed,
  },
  {
    id: 'varied-start-sprint', name: { de: 'Varied-Start-Sprints', en: 'Varied-Start Sprints' }, domain: 'speed', difficulty: 2, quality: 'Speed',
    steps: ['Aus seitlicher oder rückwärtiger Position starten.', 'Schnell in die Sprintrichtung umsetzen.', 'Kurz und explosiv beschleunigen.'],
    formTips: ['Tennisnah: Start aus jeder Lage.', 'Erster Schritt sofort in die Laufrichtung.'],
    mistakes: ['Umständliche Umsetzbewegung.', 'Antizipieren statt reagieren.'],
    variants: { gym: 'Hütchen für Startsignale.', home: 'Court / Park.', none: 'Selbst-Ansage der Startlage.' },
    dosage: D.speed,
  },
  {
    id: 'max-velocity-sprint', name: { de: '30–40 m Max-Velocity', en: '30–40 m Max Velocity' }, domain: 'speed', difficulty: 3, quality: 'Speed',
    steps: ['Sauber beschleunigen und aufrichten.', 'In die maximale Geschwindigkeit übergehen.', 'Top-Speed über 30–40 m halten.'],
    formTips: ['Top-Speed: aufrecht, hohe Frequenz.', 'Voll erholt arbeiten.'],
    mistakes: ['Verkrampfen bei Top-Speed.', 'Pausen zu kurz.'],
    variants: { gym: 'Laufbahn / lange Halle.', home: 'Freifläche / Park.', none: 'Identisch – nur Platz nötig.' },
    dosage: D.speed,
  },
  {
    id: 'hill-sprint', name: { de: 'Berg-/Steigungssprints', en: 'Hill Sprints' }, domain: 'speed', difficulty: 2, quality: 'Speed',
    steps: ['Leichte Steigung wählen.', 'Kraftvoll bergauf sprinten.', 'Locker zurückgehen als Pause.'],
    formTips: ['Kraftvoll und gelenkschonend.', 'Flacher Körperwinkel, kräftiger Abdruck.'],
    mistakes: ['Zu steile Steigung, Technik bricht.', 'Pausen zu kurz.'],
    variants: { gym: 'Laufband mit Steigung.', home: 'Hügel oder Rampe in der Nähe.', none: 'Treppen-Sprints als Ersatz.' },
    dosage: D.speed,
  },
  {
    id: 'resisted-band-sprint', name: { de: 'Resisted Band Sprint', en: 'Resisted Band Sprint' }, domain: 'speed', difficulty: 3, quality: 'Speed',
    steps: ['Band um die Hüfte, Partner hält gegen.', 'Gegen den Widerstand flach beschleunigen.', 'Über 10–15 m kraftvoll durchziehen.'],
    formTips: ['Verstärkt die Abdruckkraft.', 'Körperwinkel flach halten.'],
    mistakes: ['Zu viel Widerstand, aufrichten.', 'Schritte werden zu kurz.'],
    variants: { gym: 'Sprint-Band mit Gurt.', home: 'Band + Partner.', none: 'Handtuch vom Partner gehalten.' },
    dosage: D.speed,
  },
  {
    id: 'sled-push', name: { de: 'Schlitten schieben/ziehen', en: 'Sled Push / Pull' }, domain: 'speed', difficulty: 3, quality: 'Speed',
    steps: ['Last sicher fassen, Körper schräg.', 'Mit kraftvollen Schritten anschieben/-ziehen.', 'Über 10–20 m kontrolliert durchziehen.'],
    formTips: ['Fortgeschrittene Abdruckkraft.', 'Konstanter, flacher Druck.'],
    mistakes: ['Last zu schwer, Schritte stocken.', 'Aufrichten zu früh.'],
    variants: { gym: 'Prowler / Sled.', home: 'Beladener Wäschekorb auf glattem Boden.', none: 'Reifen oder Hügelsprints als Ersatz.' },
    dosage: D.speed,
  },
  {
    id: 'flying-sprint', name: { de: 'Flying 10–20 m', en: 'Flying 10–20 m' }, domain: 'speed', difficulty: 3, quality: 'Speed',
    steps: ['Über 15–20 m sauber auf Tempo bringen.', 'In der Flugzone Top-Speed messen/halten.', 'Locker auslaufen.'],
    formTips: ['Reines Top-End, fortgeschritten.', 'Entspannt schnell, hohe Frequenz.'],
    mistakes: ['Verkrampfen in der Flugzone.', 'Anlauf zu kurz.'],
    variants: { gym: 'Laufbahn mit Marken.', home: 'Freifläche.', none: 'Identisch – nur Platz nötig.' },
    dosage: D.speed,
  },

  // ── 5.6 Agilität & Richtungswechsel ───────────────────────────────────────
  {
    id: 'lateral-shuffle', name: { de: 'Lateral Shuffle', en: 'Lateral Shuffle' }, domain: 'agility', difficulty: 1, quality: 'Agilität',
    steps: ['Tiefe Athletikposition einnehmen.', 'Seitlich shufflen, Füße kreuzen nicht.', 'An der Marke stoppen, Richtung wechseln.'],
    formTips: ['Tief bleiben, Schwerpunkt unten.', 'Kurze, schnelle Bodenkontakte.'],
    mistakes: ['Aufrichten zwischen den Schritten.', 'Füße kreuzen.'],
    variants: { gym: '2 Hütchen als Marken.', home: 'Zwei Marken im Park.', none: 'Schatten-Shuffle ohne Marken.' },
    dosage: D.agility,
  },
  {
    id: 'ladder-both-in', name: { de: 'Leiter – beide Füße rein', en: 'Ladder – Both Feet In' }, domain: 'agility', difficulty: 1, quality: 'Agilität',
    steps: ['Vor der Leiter, tiefe Position.', 'Beide Füße nacheinander in jedes Feld.', 'Schnelle, saubere Bodenkontakte.'],
    formTips: ['Fußkoordination & Frequenz.', 'Auf dem Vorfuß bleiben.'],
    mistakes: ['Auf die Leiter treten.', 'Aufrechte, steife Haltung.'],
    variants: { gym: 'Koordinationsleiter.', home: 'Tape oder Kreide-Felder.', none: 'Gedachte Felder am Boden.' },
    dosage: D.agility,
  },
  {
    id: 'ladder-icky-shuffle', name: { de: 'Leiter – Icky Shuffle', en: 'Ladder – Icky Shuffle' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['Rein-rein-raus-Muster seitlich durch die Leiter.', 'Rhythmus konstant halten.', 'Tempo steigern, sauber bleiben.'],
    formTips: ['Rhythmus vor Speed aufbauen.', 'Vorfußkontakt, tiefe Hüfte.'],
    mistakes: ['Muster verlieren.', 'Zu früh zu schnell.'],
    variants: { gym: 'Koordinationsleiter.', home: 'Tape-Felder am Boden.', none: 'Gedachte Felder, gleiches Muster.' },
    dosage: D.agility,
  },
  {
    id: 'shuffle-stop', name: { de: 'Shuffle mit abruptem Stopp', en: 'Shuffle with Sharp Stop' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['Seitlich shufflen bis zur Marke.', 'Abrupt abbremsen und stabilisieren.', 'Explosiv in die Gegenrichtung.'],
    formTips: ['Deceleration ist der Schlüssel.', 'Breite Basis beim Stoppen.'],
    mistakes: ['Über die Marke hinausrutschen.', 'Aufrichten beim Bremsen.'],
    variants: { gym: '2 Hütchen.', home: 'Zwei Marken.', none: 'Schatten-Shuffle mit Stopp.' },
    dosage: D.agility,
  },
  {
    id: 'decel-drill', name: { de: 'Decel-Drill', en: 'Deceleration Drill' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['5–10 m antreten/sprinten.', 'In wenigen Schritten kontrolliert stoppen.', 'Stabil und tief ausbalancieren.'],
    formTips: ['Sauberes Bremsen schützt Knie & Sprunggelenk.', 'Hüfte sinkt, Schwerpunkt zurück.'],
    mistakes: ['Mit gestreckten Beinen bremsen.', 'Stoppweg zu lang.'],
    variants: { gym: 'Hütchen als Bremsmarke.', home: 'Marke im Park.', none: 'Auf Ansage selbst stoppen.' },
    dosage: D.agility,
  },
  {
    id: 'figure-8', name: { de: 'Figure-8-Hütchenlauf', en: 'Figure-8 Drill' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['Zwei Marken im Abstand aufstellen.', 'In einer Acht herumlaufen.', 'Enge, tiefe Kurven, Tempo halten.'],
    formTips: ['Kurvenlauf & Körperneigung.', 'Innen tief, Blick voraus.'],
    mistakes: ['Zu weite Kurven.', 'Oberkörper aufrecht.'],
    variants: { gym: '2 Hütchen.', home: 'Zwei Flaschen.', none: 'Zwei beliebige Marken.' },
    dosage: D.agility,
  },
  {
    id: 't-test', name: { de: 'T-Test', en: 'T-Test' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['4 Hütchen im T aufstellen.', 'Vor, seitlich shuffeln, zurück.', 'Saubere Richtungswechsel an jedem Hütchen.'],
    formTips: ['Standardisierter Agilitätstest.', 'Hütchen mit der Hand antippen.'],
    mistakes: ['Beim Shuffle Füße kreuzen.', 'Hütchen auslassen.'],
    variants: { gym: '4 Hütchen.', home: '4 Flaschen/Marken.', none: 'Tape-Marken am Boden.' },
    dosage: D.agility,
  },
  {
    id: 'pro-agility', name: { de: 'Pro-Agility / 5-10-5', en: 'Pro-Agility / 5-10-5' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['Mittig starten, 5 yd zur einen Seite.', 'Stoppen, 10 yd zur anderen Seite.', 'Stoppen, 5 yd zurück zur Mitte.'],
    formTips: ['Klassischer 180°-COD-Test.', 'Tief abbremsen, explosiv abdrücken.'],
    mistakes: ['Über die Linie hinausbremsen.', 'Aufrichten in der Wende.'],
    variants: { gym: '3 Hütchen.', home: '3 Marken im Park.', none: 'Tape-Linien am Boden.' },
    dosage: D.agility,
  },
  {
    id: 'five-0-five', name: { de: '5-0-5', en: '5-0-5' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['Anlauf nehmen, an der Marke 180° wenden.', 'Über das Standbein explosiv abdrücken.', 'Zurück durch das Tor sprinten.'],
    formTips: ['Isolierte 180°-Wende.', 'Tiefer Schwerpunkt in der Wende.'],
    mistakes: ['Zu hoher Schwerpunkt.', 'Wende mit zu vielen Schritten.'],
    variants: { gym: '2 Hütchen.', home: 'Zwei Marken.', none: 'Tape-Marken am Boden.' },
    dosage: D.agility,
  },
  {
    id: 'spider-drill', name: { de: 'Spider Drill', en: 'Spider Drill' }, domain: 'agility', difficulty: 2, quality: 'Agilität',
    steps: ['5 Bälle an den Court-Punkten verteilen.', 'Von der Mitte zu jedem Ball sprinten.', 'Ball holen, zurück zur Mitte.'],
    formTips: ['Tennis-spezifischste Agilität (ICC 0,93–0,95).', 'Tiefe Position bei Richtungswechseln.'],
    mistakes: ['Aufrecht laufen.', 'Bremsweg zu lang.'],
    variants: { gym: 'Hütchen statt Bälle.', home: 'Markierungen mit Socken/Tape.', none: 'Schattendrill nach Ansage.' },
    dosage: D.agility,
  },
  {
    id: 'mirror-drill', name: { de: 'Partner-Spiegel-Drill', en: 'Partner Mirror Drill' }, domain: 'agility', difficulty: 3, quality: 'Agilität',
    steps: ['Gegenüber dem Partner in Athletikposition.', 'Partner bewegt sich, du spiegelst sofort.', 'Tief bleiben, schnell reagieren.'],
    formTips: ['Reaktive Agilität ohne Vorplanung.', 'Auf den Partner reagieren, nicht raten.'],
    mistakes: ['Bewegung antizipieren.', 'Aufrichten zwischen Reaktionen.'],
    variants: { gym: '2 Hütchen als Grenzen + Partner.', home: 'Marken + Partner.', none: 'Partner-Spiegel ohne Marken.' },
    dosage: D.agility,
  },
  {
    id: 'ball-drop-reaction', name: { de: 'Ball-Drop-Reaktionssprint', en: 'Ball-Drop Reaction' }, domain: 'agility', difficulty: 3, quality: 'Agilität',
    steps: ['Partner hält Ball auf Armlänge.', 'Auf das Loslassen reagieren und sprinten.', 'Ball vor dem zweiten Aufprall fangen.'],
    formTips: ['Schult die Erststep-Reaktion.', 'Erst auf den Drop, dann explodieren.'],
    mistakes: ['Vor dem Loslassen starten.', 'Träger erster Schritt.'],
    variants: { gym: 'Reaktionsball + Partner.', home: 'Tennisball + Partner.', none: 'Auf Zuruf statt Ball reagieren.' },
    dosage: D.agility,
  },
  {
    id: 'call-the-cone', name: { de: 'Call-the-Cone-Cut', en: 'Call-the-Cone Cut' }, domain: 'agility', difficulty: 3, quality: 'Agilität',
    steps: ['Mehrere farbige Hütchen aufstellen.', 'Auf Zuruf/Licht zum genannten Hütchen cutten.', 'Sofort zurück und neu reagieren.'],
    formTips: ['Reaktive Entscheidung unter Tempo.', 'Tiefer Cut, sauberer Abdruck.'],
    mistakes: ['Auf das Signal antizipieren.', 'Cut zu hoch und langsam.'],
    variants: { gym: 'Reaktionslichter / farbige Hütchen.', home: 'Farbige Marken + Zuruf.', none: 'Partner ruft Richtungen.' },
    dosage: D.agility,
  },
  {
    id: 'reactive-bound-cut-combo', name: { de: 'Reaktive Bound-and-Cut-Kombi', en: 'Reactive Bound-and-Cut Combo' }, domain: 'agility', difficulty: 3, quality: 'Agilität',
    steps: ['Lateralen Bound springen und stabil landen.', 'Auf Signal in einen Sprint/Cut umsetzen.', 'Mehrere Wechsel kombinieren.'],
    formTips: ['Koppelt Plyometrie und reaktive Agilität.', 'Saubere Landung als Basis jedes Cuts.'],
    mistakes: ['Landung überspringen.', 'Signal antizipieren.'],
    variants: { gym: 'Hütchen + Partner-Signal.', home: 'Marken + Zuruf.', none: 'Selbst-Ansage als Signal.' },
    dosage: D.agility,
  },

  // ── 5.7 Aerobe & anaerobe Kondition ───────────────────────────────────────
  {
    id: 'aerobic-base', name: { de: 'Aerobe Basis 20–40 min', en: 'Aerobic Base 20–40 min' }, domain: 'aerobic', difficulty: 1, quality: 'Kondition',
    steps: ['Lockeres, gleichmäßiges Tempo wählen.', 'Rad oder Lauf über 20–40 min.', 'Im plauderfähigen Bereich bleiben.'],
    formTips: ['Baut die aerobe Grundlage auf.', 'Gleichmäßig, kontrolliert atmen.'],
    mistakes: ['Tempo zu hoch ansetzen.', 'Zu seltene Grundlageneinheiten.'],
    variants: { gym: 'Ergometer / Laufband.', home: 'Lauf- oder Radrunde.', none: 'Zügiges Gehen-Joggen.' },
    dosage: { intensity: 'locker', reps: '20–40 min', sets: '1', rest: '–' },
  },
  {
    id: 'tempo-intervals', name: { de: 'Tempo-Intervalle 30s/30s', en: 'Tempo Intervals 30s/30s' }, domain: 'aerobic', difficulty: 1, quality: 'Kondition',
    steps: ['30 s zügig, 30 s locker im Wechsel.', 'Über 10–20 min wiederholen.', 'Tempo kontrolliert, nicht maximal.'],
    formTips: ['Brücke zwischen Grundlage und Intervall.', 'Sauberer, gleichmäßiger Rhythmus.'],
    mistakes: ['Schnellphasen zu hart.', 'Pausen verschleppen.'],
    variants: { gym: 'Laufband / Ergometer.', home: 'Lauf- oder Radstrecke.', none: 'Shuttle-Joggen im Wechsel.' },
    dosage: { intensity: 'zügig', reps: '30s/30s', sets: '10–20 min', rest: 'aktiv' },
  },
  {
    id: 'point-simulation', name: { de: 'Punktsimulation 6–8 s / 20 s', en: 'Point Simulation 6–8s / 20s' }, domain: 'aerobic', difficulty: 2, quality: 'Kondition',
    steps: ['6–8 s explosive, multidirektionale Arbeit.', '~20 s aktive Pause (≈1:3).', '6–8 Wiederholungen pro Satz.'],
    formTips: ['Bildet die Ballwechsel-Belastung exakt nach.', 'Kurz, intensiv, richtungsreich.'],
    mistakes: ['Belastung zu lang ansetzen.', 'Pausen zu kurz, Qualität fällt.'],
    variants: { gym: 'Hütchen-Muster in der Halle.', home: 'Court / Park mit Marken.', none: 'In-Place-Sprints & Cuts.' },
    dosage: { intensity: '~max', reps: '6–8 s', sets: '6–8', rest: '~20 s (1:3)' },
  },
  {
    id: 'repeated-effort', name: { de: 'Repeated-Effort 20–30 s', en: 'Repeated-Effort 20–30s' }, domain: 'aerobic', difficulty: 2, quality: 'Kondition',
    steps: ['20–30 s harte, multidirektionale Arbeit.', '20–30 s Pause, 6–8 Wiederholungen.', '2–3 min Pause zwischen den Drills.'],
    formTips: ['Anaerobe Kapazität tennisnah.', 'Intensität über die Wiederholungen halten.'],
    mistakes: ['Erste Wiederholungen überziehen.', 'Drill-Pausen weglassen.'],
    variants: { gym: 'Hütchen-Shuttles.', home: 'Court / Park.', none: 'Burpee-/Sprint-Mix auf der Stelle.' },
    dosage: { intensity: 'hart', reps: '20–30 s', sets: '6–8', rest: '20–30 s' },
  },
  {
    id: 'on-court-suicides', name: { de: 'On-Court-Suicides', en: 'On-Court Suicides' }, domain: 'aerobic', difficulty: 2, quality: 'Kondition',
    steps: ['Von der Grundlinie zu den Linien sprinten.', 'Jede Linie antippen, zurück.', '5–20 Wiederholungen mit Pause.'],
    formTips: ['Court-spezifische Suicides/Liniensprints.', 'Saubere Stopps an jeder Linie.'],
    mistakes: ['Linien nicht antippen.', 'Pausen unkontrolliert.'],
    variants: { gym: 'Hallenlinien.', home: 'Park-Markierungen.', none: 'Selbst gesetzte Marken.' },
    dosage: { intensity: 'hart', reps: '5–20 Wdh', sets: '1–3', rest: '30–90 s' },
  },
  {
    id: 'spider-run-interval', name: { de: 'Spider Run als Intervall', en: 'Spider Run Interval' }, domain: 'aerobic', difficulty: 2, quality: 'Kondition',
    steps: ['Spider-Run-Muster mit 5 Bällen laufen.', '3–4 Sätze als Intervall.', '~90 s Pause zwischen den Sätzen.'],
    formTips: ['Verbindet Agilität mit Kondition.', 'Tempo über alle Sätze halten.'],
    mistakes: ['Erster Satz zu hart.', 'Technik unter Ermüdung schludrig.'],
    variants: { gym: '5 Hütchen.', home: '5 Marken auf dem Court.', none: 'Stern-Markierungen am Boden.' },
    dosage: { intensity: 'hart', reps: '1 Lauf', sets: '3–4', rest: '~90 s' },
  },
  {
    id: 'court-pattern', name: { de: 'Star/Box/Big-X-Muster', en: 'Star / Box / Big-X Pattern' }, domain: 'aerobic', difficulty: 2, quality: 'Kondition',
    steps: ['Hütchen im Stern-/Box-/X-Muster setzen.', 'Multidirektional unter Ermüdung abarbeiten.', 'Saubere Richtungswechsel halten.'],
    formTips: ['Multidirektionale Ausdauer.', 'Auch müde tiefe Position halten.'],
    mistakes: ['Muster verkürzen.', 'Aufrichten unter Ermüdung.'],
    variants: { gym: 'Hütchen-Setup.', home: 'Marken im Park.', none: 'Tape-Muster am Boden.' },
    dosage: { intensity: 'hart', reps: '30–45 s', sets: '4–6', rest: '1:2' },
  },
  {
    id: 'hiit-bike-run', name: { de: 'Rad/Lauf-HIIT', en: 'Bike/Run HIIT' }, domain: 'aerobic', difficulty: 2, quality: 'Kondition',
    steps: ['~15–30 s hart antreten.', 'Gleich lange Pause (matched).', 'Intervalle wiederholen.'],
    formTips: ['+28,9 % tennisspezifische Ausdauer (Studie).', 'Harte Phasen wirklich hart.'],
    mistakes: ['Intensität zu niedrig.', 'Pausen zu lang.'],
    variants: { gym: 'Ergometer / Laufband-Intervalle.', home: 'Rad- oder Laufintervalle.', none: 'Hügel-/Treppen-Repeats.' },
    dosage: { intensity: 'sehr hart', reps: '15–30 s', sets: '6–10', rest: '1:1' },
  },
  {
    id: 'sprint-interval-sit', name: { de: 'SIT / RSA-Sprints', en: 'Sprint Interval / RSA' }, domain: 'aerobic', difficulty: 3, quality: 'Kondition',
    steps: ['6–8 × 20–30 m maximal sprinten.', 'Nur 20–30 s Pause dazwischen.', '2–3×/Woche in Blöcken.'],
    formTips: ['RST senkt die Sprintzeit (−3,8 %).', 'Jeder Sprint maximal.'],
    mistakes: ['Tempo nicht maximal.', 'Ganzjährig statt in Blöcken.'],
    variants: { gym: 'Lange Halle / Bahn.', home: 'Park / Court.', none: 'Identisch – nur Platz nötig.' },
    dosage: { intensity: 'max', reps: '20–30 m', sets: '6–8', rest: '20–30 s' },
  },
  {
    id: 'repeated-sprints', name: { de: 'Wiederholte Sprints', en: 'Repeated Sprints' }, domain: 'aerobic', difficulty: 3, quality: 'Kondition',
    steps: ['Kurze Sprints mit unvollständiger Erholung.', 'Pausenverhältnis ~1:2–1:3.', 'Über mehrere Sätze halten.'],
    formTips: ['Wiederholte Sprintfähigkeit (RSA).', 'Zeit über die Sätze stabil halten.'],
    mistakes: ['Zu lange Pausen (kein RSA-Reiz).', 'Erste Sprints überziehen.'],
    variants: { gym: 'Bahn mit Marken.', home: 'Freifläche.', none: 'Identisch – nur Platz nötig.' },
    dosage: { intensity: 'max', reps: '20–40 m', sets: '8–12', rest: '1:2–1:3' },
  },

  // ── 5.8 Mobilität & Prehab ────────────────────────────────────────────────
  {
    id: 'worlds-greatest-stretch', name: { de: "World's Greatest Stretch", en: "World's Greatest Stretch" }, domain: 'mobility', difficulty: 1, quality: 'Mobility',
    steps: ['Tiefer Ausfallschritt nach vorn.', 'Ellbogen Richtung vorderem Fuß.', 'Oberkörper zur vorderen Seite öffnen.'],
    formTips: ['Ruhig atmen, in die Dehnung sinken.', 'Hintere Hüfte aktiv strecken.'],
    mistakes: ['Hektisch durchhuschen.', 'Hinteres Knie ganz am Boden ziehen.'],
    variants: { gym: 'Im Warm-up-Bereich.', home: 'Überall ohne Equipment.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.mobility,
  },
  {
    id: 'knee-to-wall', name: { de: 'Knee-to-Wall (Sprunggelenk)', en: 'Knee-to-Wall' }, domain: 'mobility', difficulty: 1, quality: 'Mobility',
    steps: ['Fuß vor der Wand, Zehe in fixem Abstand.', 'Knie über die Zehe Richtung Wand schieben.', 'Ferse bleibt am Boden, halten.'],
    formTips: ['Sprunggelenks-Dorsalflexion für Cuts & Stopps.', 'Ferse darf nicht abheben.'],
    mistakes: ['Ferse hebt ab.', 'Knie kippt nach innen.'],
    variants: { gym: 'An der Wand mit Maßband.', home: 'Türrahmen oder Wand.', none: 'Identisch – nur eine Wand nötig.' },
    dosage: D.mobility,
  },
  {
    id: 'thoracic-open-book', name: { de: 'BWS Open-Book', en: 'Thoracic Open-Book' }, domain: 'mobility', difficulty: 1, quality: 'Mobility',
    steps: ['Seitlage, Knie angewinkelt, Arme vorn gestapelt.', 'Oberen Arm öffnend nach hinten führen.', 'Brustwirbelsäule aufdrehen, zurück.'],
    formTips: ['BWS-Rotation für Schlag & Aufschlag.', 'Becken bleibt stabil, Bewegung aus der Brust.'],
    mistakes: ['Aus der Lende drehen.', 'Knie heben ab.'],
    variants: { gym: 'Auf der Matte.', home: 'Überall am Boden.', none: 'Identisch – kein Equipment nötig.' },
    dosage: D.mobility,
  },
];
